ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from ecommerce import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop import views

app_name = "shop"

urlpatterns = [
    path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('search/', views.search, name="search"),
    path('<slug>/cart/', views.cart, name="cart"),
    path('mycart/', views.mycart, name="mycart"),
    path('checkout/', views.checkout, name="checkout"),
    path('<slug>/', views.detail, name="detail"),
    path('categories/<slug>/', views.categories, name="categories"),
    path('api/products/', views.api_products, name="api_products"),
]

shop/models.py
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to="categories", blank=True)
    description = models.TextField(blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"


class Product(models.Model):
    name = models.CharField(max_length=250)
    slug = AutoSlugField(populate_from='name')
    image = models.ImageField(upload_to="products", blank=True)
    brand = models.CharField(max_length=250, blank=True)
    shipping = models.CharField(max_length=250, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=15, decimal_places=2, default=0.0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.IntegerField(default=10, validators=[MaxValueValidator(10), MinValueValidator(1)])
    review = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.review

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from . import models


class ReviewForm(forms.ModelForm):
    class Meta:
        fields = ["rate", "review"]
        model = models.Review


class SigninForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

shop/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect

# Create your views here.
from rest_framework.decorators import api_view
from rest_framework.response import Response

from shop.forms import ReviewForm, SignupForm, SigninForm
from shop.models import Product, Category
from shop.serializer import ProductSerializer


def home(request):
    # if request.META['HTTP_HOST'] != "ecommerce.hem.xyz.np":
    #     return redirect("http://ecommerce.hem.xyz.np")
    products = Product.objects.filter(active=True)
    categories = Category.objects.filter(active=True)
    context = {"products": products, "categories": categories}
    return render(request, "shop/home.html", context)


def search(request):
    q = request.GET["q"]
    products = Product.objects.filter(active=True, name__icontains=q)
    categories = Category.objects.filter(active=True)
    context = {"products": products,
               "categories": categories,
               "title": q + " - search"}
    return render(request, "shop/list.html", context)


def categories(request, slug):
    cat = Category.objects.get(slug=slug)
    products = Product.objects.filter(active=True, category=cat)
    categories = Category.objects.filter(active=True)
    context = {"products":products, "categories":categories, "title":cat.name + " - Categories"}
    return render(request, "shop/list.html", context)


def detail(request, slug):
    product = Product.objects.get(active=True, slug=slug)
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            messages.success(request, "Review saved")
        else:
            messages.error(request, "Invalid form")
    else:
        form = ReviewForm()


    categories = Category.objects.filter(active=True)
    context = {"product" : product,
               "categories":categories,
               "form": form}
    return render(request, "shop/detail.html", context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, "User saved")
            return redirect("shop:signin")
        else:
            messages.error(request, "Error in form")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "shop/signup.html", context)


def signin(request):
    if request.method=="POST":
        form = SigninForm(request.POST)
        # username = req.POST["username"]
        # password = req.POST["password"]
        username = form["username"].value()
        password = form["password"].value()
        user = authenticate(request, username=username,  password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully logged in")
            return redirect("shop:home")
        else:
            messages.error(request, "Invalid Username or Password")
    else:
        form = SigninForm()
    context = {"form": form}
    return render(request, "shop/signin.html", context)


def signout(request):
    logout(request)
    return redirect("shop:signin")


def cart(request, slug):
    """
        data = {"items" : ["slug1", "slug2"],
                "price" : 12342,
                "count" : 5
                }
        request.session["data"] = data
        """
    product = Product.objects.get(slug=slug)
    inital = {"items":[],"price":0.0,"count":0}
    session = request.session.get("data", inital)
    if slug in session["items"]:
        messages.error(request, "Already added to cart")
    else:
        session["items"].append(slug)
        session["price"] += float(product.price)
        session["count"] += 1
        request.session["data"] = session
        messages.success(request, "Added successfully")
    return redirect("shop:detail", slug)


def mycart(request):
    sess = request.session.get("data", {"items":[]})
    products = Product.objects.filter(active=True, slug__in=sess["items"])
    categories = Category.objects.filter(active=True)
    context = {"products": products,
               "categories": categories,
               "title": "My Cart"}
    return render(request, "shop/list.html", context)


def checkout(request):
    request.session.pop('data', None)
    return redirect("/")

@api_view(['GET'])
def api_products(request):
    query = request.GET.get("q", "")
    products = Product.objects.filter(Q(name__contains=query) | Q(description__contains=query))
    serializer = ProductSerializer(products, many=True)
    return Response(serializer.data)

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load bootstrap4 %}
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Shop Homepage - Bootstrap Template{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "shop/css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "shop/css/shop-homepage.css" %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">Ecommerce Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url "shop:home" %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/hereshem/django-ecommerce">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "shop:api_products" %}">APIs</a>
            </li>
              <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url "shop:signout" %}">Sign Out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url "shop:signin" %}">Sign In</a>
                            <a class="dropdown-item" href="{% url "shop:signup" %}">Signup</a>
                        {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url "shop:checkout" %}">Checkout</a>

                    </div>
                </li>
          </ul>

            <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
            </form>
            <a href="/mycart" class="btn btn-success">🛒{{ request.session.data.count }} Item{{ request.session.data.count|pluralize }}</a>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <div class="col-lg-3">

          <h1 class="my-4">Ecommerce Shop</h1>
          <div class="list-group">
              {% for c in categories %}
                  <a href="{% url "shop:categories" c.slug %}" class="list-group-item">{{ c.name }}</a>
              {% endfor %}
{#            <a href="#" class="list-group-item">Category 1</a>#}
{#            <a href="#" class="list-group-item">Category 2</a>#}
{#            <a href="#" class="list-group-item">Category 3</a>#}
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9 mt-3">
        {% bootstrap_messages %}
{% block header %}{% endblock %}


              {% block content %}
<div class="row mt-3">
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item One</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Two</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Three</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Four</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Five</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur! Lorem ipsum dolor sit amet.</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>

            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">Item Six</a>
                  </h4>
                  <h5>$24.99</h5>
                  <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>


          </div>
          <!-- /.row -->
        {% endblock %}

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Ecommerce Shop 2018</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static "shop/js/jquery.min.js" %}" type="text/javascript"></script>
    <script src="{% static "shop/js/bootstrap.min.js" %}" type="text/javascript"></script>

  </body>

</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% block title %}Ecommerce Home Page{% endblock  %}
{% load bootstrap4 %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
          <img class="img-fluid" src="/media/{{ product.image }}" alt="">
        </div>

        <div class="col-md-4">
          <h3 class="my-3">{{ product.name|title }}</h3>
          <p>{{ product.description }}</p>
          <h3 class="my-3">Project Details</h3>
          <ul>
            <li>Lorem Ipsum</li>
            <li>Dolor Sit Amet</li>
            <li>Consectetur</li>
            <li>Adipiscing Elit</li>
          </ul>
            <form action="{% url "shop:cart" product.slug%}">
                <input type="submit" class="btn btn-danger" value="Add to cart">
            </form>
        </div>
</div>
        <hr>
        <div class="row">
        {% for item in product.review_set.all %}
            <div class="card mb-3 w-100">
          <div class="card-body">
            <h5 class="card-title">{{ item.rate }} star{{ item.rate|pluralize }}</h5>
            <p class="card-text">{{ item.review}}</p>
            <p class="card-text">By : {{ item.user.username}}</p>
          </div>
          <div class="card-footer text-muted">
            {{ item.created|timesince }} ago
          </div>
        </div>
        {% endfor %}
        </div>
    <div class="row mb-5">
    <form method="post">
        {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success">
    </form>
    </div>
{% endblock %}

shop/templates/shop/home.html
{% extends "shop/base.html" %}
{% block title %}eCommerce Home Page{% endblock  %}

{% block content %}
    <div class="row">
{% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="/media/{{ item.image }}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url "shop:detail" item.slug %}">{{ item.name|title }}</a>
                  </h4>
                  <h5>Rs. {{ item.price|floatformat:"2" }}</h5>
                  <p class="card-text">{{ item.description }}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><a class="btn btn-success" href="{% url "shop:cart" item.slug %}">Add to Cart</a></small>
                </div>
              </div>
            </div>
{% endfor %}
</div>
{% endblock %}

{% block header %}
          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="//placehold.it/900x350" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="//placehold.it/900x350" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="//placehold.it/900x350" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
{% endblock %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% block title %}{{ title }}{% endblock  %}

{% block content %}
    <div class="row">
{% for item in products %}
    <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="#"><img class="card-img-top" src="/media/{{ item.image }}" alt=""></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url "shop:detail" item.slug %}">{{ item.name|title }}</a>
                  </h4>
                  <h5>Rs. {{ item.price|floatformat:"2" }}</h5>
                  <p class="card-text">{{ item.description }}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted"><a class="btn btn-success" href="{% url "shop:cart" item.slug %}">Add to Cart</a></small>
                </div>
              </div>
            </div>
{% empty %}
    <div class="card w-100">
    <div class="card-body">
        <h4>Item not available</h4>
    </div>
    </div>
{% endfor %}
    </div>

{% endblock %}

shop/templates/shop/signin.html
{#{% extends "blogs/base.html" %}#}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}


<title>{% block title %}Login to eCommerce Shop{% endblock %}</title>


<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-4 offset-lg-4 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Login to eCommerce Shop
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    {#    {{ form.as_p }}#}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Sign In">
                        <a href="{% url "shop:signup" %}" class="small">Sign Up</a>
                        <a href="/" class="float-right small">Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>


</div>

shop/templates/shop/signup.html
{#{% extends "blogs/base.html" %}#}

{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<title>{% block title %}SignUp to eCommerce Shop{% endblock %}</title>

<div class="container">
    {% bootstrap_messages %}
    <div class="row">
        <div class="col-lg-6 offset-lg-3 col-sm-10 offset-sm-1">
            <div class="card my-5">
                <div class="card-header text-center">
                    Sign Up to eCommerce Shop
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    {#    {{ form.as_p }}#}
                        <input type="submit" class="btn btn-success text-center w-100 mb-3" value="Sign Up">
                        <a href="{% url "shop:signin" %}" class="small">Sign In</a>
                        <a href="/" class="float-right small">Home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>